# Generated by Django 5.2.8 on 2025-11-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
