# Generated by Django 5.2.8 on 2025-11-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_gallery_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='draft',
            new_name='is_draft',
        ),
    ]
